# Change these first
owner: kenundrem # Your GitHub organization or username, where this repository lives
repo: ccsuptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Microsoft 365
    url: https://status.cloud.microsoft/
  - name: Adobe
    url: https://status.adobe.com/
  - name: Apple Services
    url: https://www.apple.com/support/systemstatus/
  - name: AWS
    url: https://health.aws.amazon.com/health/status
  - name: Odoo
    url: https://www.saashub.com/odoo-status
  - name: Zoom
    url: https://www.zoomstatus.com/
  - name: Google Cloud Services
    url: https://status.cloud.google.com/
  - name: Microsoft Azure
    url: https://azure.status.microsoft/en-us/status

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /ccsuptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CCS Custom Uptime Monitor
  introTitle: "**CCS Custom Uptime Monitor** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This data updated every 5 minutes
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
