# Change these first
owner: kenundrem # Your GitHub organization or username, where this repository lives
repo: ccsuptime # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Microsoft 365
    url: https://github.com/kenundrem/ccsuptime/blob/master/m_365_status_dashboard_single_file.html
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /ccsuptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CCS Custom Uptime Monitor
  introTitle: "**CCS Custom Uptime Monitor** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This data updated every 5 minutes
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
